import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" w-full bg-teal-500 text-white text-4xl font-bold flex justify-center place-items-center gap-5 p-5" >


          <Link href="/">Home Page</Link>
          <Link href="/articles">Articles</Link>
          <Link href="/posts">Posts</Link>

        </nav>
        {children}</body>
    </html>
  );
}
